### ISSUE TITLE
Run Tests

### ISSUE THREAD

**Issue by balasankarc** [baschtl/devise-token_authenticatable#18]
Hi,
Can I know how to run tests for this gem? `$ bundle exec rake` gave me the following output

rake aborted!
Don't know how to build task 'default'

(See full trace by running task with --trace)

**Comment by baschtl** [comment]
`bundle exec rspec` does the trick.

**Comment by balasankarc** [comment]
Hi,
I am packaging this gem for Debian (as part of Diaspora packaging). I don't quite understand how the tests are being run. What does the single line in Rakefile actually do? Who decides which all files in spec directory are to be run?? Is there any documentation that may help me here?

**Comment by baschtl** [comment]
The line in the `Rakefile` makes some rake tasks available that are provided by bundler: https://github.com/bundler/bundler/blob/master/lib/bundler/gem_tasks.rb.

`bundle exec rspec` just runs all the specs. If you want to run a specific file you give the relative path as a parameter to the `bundle exec rspec` command. You probably want to look at the rspec documentation.
