### ISSUE TITLE
Token Authenticatable ignores "request_keys" 

### ISSUE THREAD

**Issue by brightbits** [baschtl/devise-token_authenticatable#19]
See http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Authenticatable for request_keys usage. You can basically ask it to pass extra data from the request (such as subdomain) so you can scope your lookups correctly.

The subdomain isn't passed in when using devise-token_authenticatable because of:

```ruby
        def find_for_token_authentication(conditions)
          find_for_authentication(authentication_token: conditions[Devise::TokenAuthenticatable.token_authentication_key])
        end
```

The conditions at this point contain the `subdomain`, but don't make their way in to `find_for_authentication` which in my case expects it.

**Comment by baschtl** [comment]
@brightbits Good catch! I cannot say when exactly I will have time to fix this. So, feel free to submit a PR for this. :-)

**Comment by brightbits** [comment]
Its on its way, I'm just pushing it up to github
