### ISSUE TITLE
Can't bundle from rubygems.org

### ISSUE THREAD

**Issue by ksouthworth** [baschtl/devise-token_authenticatable#26]
I added this to my gemfile

`gem 'devise-token_authenticatable', '~> 0.4'`

tried to run bundle but it's failing with an error:

> Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching

**Comment by ksouthworth** [comment]
nevermind, started working on the 27th try!

**Comment by baschtl** [comment]
@ksouthworth Great to read that. :-)
