### ISSUE TITLE
Current_user not always giving the current user

### ISSUE THREAD

**Issue by CR4567** [baschtl/devise-token_authenticatable#28]
Hi,

sry if I'm wrong but shouldn't current_user giving me the current signed in user / the user related to the auth_token?
I'm using the recent versions of devise (3.5.6) and devise-token_authenticatable (4.0.0).
It's an absolutely weird behavior when I'm logging into my App the token is generated normally and everything works like expected. But if I logout and use a different user, a new devise token is saved in database for this user, but when using current_user by API with the new token, I'm always getting the first user. Looks to me like a problem with the session or cookie but not sure at which point in the code this occurs.

Anyone else an idea ?

Thanks a lot
Chris

**Comment by baschtl** [comment]
Hey Chris,

could you give us a bit more background information about your current setup if this is still an issue for you? How do your controllers and models look like? How does your devise setup look like?

Cheers

**Comment by CR4567** [comment]
Hey,

ahh yes the "problem" still occurs. However I think problem is the wrong word. I figured out that my app generates a session cookie which is used to handle all the incoming requests after the initial login.
A new Login with a different user generates a new auth_token but if I'm using the new auth_token I still gets the data from the old user. The user with the session. 
So the issue is how to remove or invalidate the session cookie or how to ignore it when an auth_token is used.

My setup looks like:
ApplicationController: `before_filter :authenticate_user!`

Routes: 
`  devise_for :user,
             :controllers => { :registrations => 'users/registrations',
                               :confirmations => 'users/confirmations',
                               :sessions => 'devise/sessions'},
             :skip => [:sessions]`

Devise config:
```
Devise.setup do |config|
  # config.secret_key = 'bded6704e0ded221f3bd42206b566bc1ae1cac81fa7cf801db878bacb8c1b4f91c3b649eba92a1d16420a85037f119ef322adec639121823b58da431bef45332'
  config.mailer_sender = 'reichelt@easierlife.de'
  require 'devise/orm/active_record'
  # config.authentication_keys = [:email]
  # config.request_keys = []
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  # config.params_authenticatable = true
  # :database      = Support basic authentication with authentication key + password
  # config.http_authenticatable = false
  # config.http_authenticatable_on_xhr = true
  # config.http_authentication_realm = 'Application'
  # config.paranoid = true
  config.skip_session_storage = [:http_auth]
  # config.clean_up_csrf_token_on_authentication = true
  config.stretches = Rails.env.test? ? 1 : 10
  # config.pepper = 'd62f5edaa08103dd6ca05a9b877165311ddf82bbcca7872ca5d408b75bec030ca03256e72c66067bb0dc43a83f0f0def70ff628a385999a8da879c3497389873'
  # config.allow_unconfirmed_access_for = 2.days
  # config.confirm_within = 3.days
  config.reconfirmable = true
  # config.confirmation_keys = [:email]
  # config.remember_for = 2.weeks
  config.expire_all_remember_me_on_sign_out = true
  # config.extend_remember_period = false
  # config.rememberable_options = {}
  config.password_length = 8..128
  # config.email_regexp = /\A[^@]+@[^@]+\z/
  # config.timeout_in = 30.minutes
  # config.expire_auth_token_on_timeout = false
  # config.lock_strategy = :failed_attempts
  # config.unlock_keys = [:email]
  # :time  = Re-enables login after a certain amount of time (see :unlock_in below)
  # :both  = Enables both strategies
  # :none  = No unlock strategy. You should handle unlocking by yourself.
  # config.unlock_strategy = :both
  # config.maximum_attempts = 20
  # config.unlock_in = 1.hour
  config.reset_password_within = 6.hours

  config.sign_out_via = :delete
```
`

**Comment by baschtl** [comment]
Hey Chris,

you should be able to do the following in your devise setup:

```ruby
config.skip_session_storage = [:http_auth, :token_auth]
```

This should tell devise to skip persisting the session while you use token authentication. Does that make sense?

**Comment by CR4567** [comment]
Hey,

that seems to work perfectly. Thanks a lot for the support.

**Comment by baschtl** [comment]
@CR4567 Glad that I could help. I close this for now.
