### ISSUE TITLE
Config expire_auth_token_on_timeout does not work

### ISSUE THREAD

**Issue by mikwat** [baschtl/devise-token_authenticatable#30]
Setting `config.expire_auth_token_on_timeout = true` does not appear to work as expected. When a user's session times out, I would expect to see their auth token reset, but that doesn't happen in my application.

I think the problem is that, according to [Warden](http://www.rubydoc.info/github/hassox/warden/Warden/Hooks#after_set_user-instance_method), `after_set_user` hooks are called in the order of declaration and the `timeoutable` hook, which is declared first, raises an error [here](https://github.com/plataformatec/devise/blob/master/lib/devise/hooks/timeoutable.rb#L26) thus skipping later hooks.

For reference, here are the after set user hooks in my application:
```
> Warden::Manager._after_set_user
 => [
  [#<Proc:0x007feb1708e6c0@/Users/michwatt/.rvm/gems/ruby-2.1.5/gems/devise-3.5.2/lib/devise/hooks/activatable.rb:4>, {}], 
  [#<Proc:0x007feb1708caf0@/Users/michwatt/.rvm/gems/ruby-2.1.5/gems/devise-3.5.2/lib/devise/hooks/csrf_cleaner.rb:1>, {:event=>:authentication}], 
  [#<Proc:0x007feb18b37968@/Users/michwatt/.rvm/gems/ruby-2.1.5/gems/devise-3.5.2/lib/devise/hooks/rememberable.rb:1>, {:event=>[:set_user, :authentication]}], 
  [#<Proc:0x007feb17131028@/Users/michwatt/.rvm/gems/ruby-2.1.5/gems/devise-3.5.2/lib/devise/hooks/timeoutable.rb:6>, {}], 
  [#<Proc:0x007feb18ae6b08@/Users/michwatt/.rvm/gems/ruby-2.1.5/gems/devise-3.5.2/lib/devise/hooks/trackable.rb:5>, {:event=>[:set_user, :authentication]}], 
  [#<Proc:0x007feb18ac7f28@/Users/michwatt/.rvm/gems/ruby-2.1.5/gems/devise-token_authenticatable-0.4.6/lib/devise/token_authenticatable/hooks/timeoutable.rb:11>, {}]
]
```

My Gemfile (of course, `devise` must appear first):
```
gem 'devise', '3.5.2'
gem 'devise-token_authenticatable', '~> 0.4.6'
```

Is anyone else seeing this behavior?

**Comment by baschtl** [comment]
@mikwat Interesting, I see your point. I wonder why [those specs](https://github.com/baschtl/devise-token_authenticatable/blob/v0.4.6/spec/requests/devise/token_authenticatable/strategy_spec.rb#L135) do not fail then.

I do not see an option to tell Warden to insert the hook before the one given by `timeoutable` for now... Besides that it would introduce more coupling. Do you have an idea?

**Comment by mikwat** [comment]
@baschtl I think I figured out why those specs are passing (and shouldn't be):
https://github.com/baschtl/devise-token_authenticatable/pull/31

I don't have a good solution, but I think the functionality I really want is in this PR:
https://github.com/baschtl/devise-token_authenticatable/pull/25

I might try to resurrect it.

**Comment by baschtl** [comment]
Hey @mikwat,

if I get it right, what you propose is that we should drop the timeoutable hook and go for a separate solution as was proposed in #25 to decouple from the devise timeoutable module?

**Comment by mikwat** [comment]
Yes, exactly @baschtl 

I have resurrected that PR (and fixed the specs) here: https://github.com/baschtl/devise-token_authenticatable/compare/v0.4.6...TetrationAnalytics:v0.4.7 But since there is no v0.4.x branch, I don't know what to do with it.

I could make the same changes to master, but since I'm not using devise 5, it's not really important to me at this point.

**Comment by baschtl** [comment]
Ok, I try to get your changes integrated to the current master when I find the time. I think that the timeoutable hook should be removed again.

**Comment by mikwat** [comment]
Sounds good @baschtl 

What do you think about releasing a v0.4.7 with my changes (for compatibility with devise 3.5.2)?

**Comment by baschtl** [comment]
@mikwat I incorporated your changes into version [0.4.9](https://rubygems.org/gems/devise-token_authenticatable/versions/0.4.9). Thanks a lot for your help and effort!

**Comment by mikwat** [comment]
Looks good, thanks @baschtl !
