### ISSUE TITLE
Devise 4.2.0

### ISSUE THREAD

**Issue by jankeesvw** [baschtl/devise-token_authenticatable#34]
There is a new version of Devise [released on 2016-07-01](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#420---2016-07-01), the [Gemspec of this gem](https://github.com/baschtl/devise-token_authenticatable/blob/99bee7d4ae0bbc694ad993b2fb5d07cef8563047/devise-token_authenticatable.gemspec#L25) tells me I can only use it with Devise < 4.2.

Is there something I can to do get this working on Devise 4.2?

**Comment by baschtl** [comment]
Hey @jankeesvw,

sure, create a PR where you adapt the gemspec accordingly. Let CI do its job and ensure that the tests are green with the recent changes in devise 4.2. :-)
