### ISSUE TITLE
Accept token authentication only?

### ISSUE THREAD

**Issue by fernandomm** [baschtl/devise-token_authenticatable#36]
In some parts of my application ( Eg.: API ) I want to accept only token authentication strategy.

But when i set "before_action: authenticate_user!" and an invalid auth token is provided, it will also check session to verify if user is already logged in.

Is there a way to disable this behavior and force token authentication?

**Comment by baschtl** [comment]
https://github.com/baschtl/devise-token_authenticatable#troubleshooting

**Comment by fernandomm** [comment]
Sorry, maybe I didn't explain it well. I already have:

```
config.skip_session_storage = [:http_auth, :token_auth]
```

In my devise.rb initializer.

When a non logged-in user use a token, a session isn't created. This is working fine.

What I'm asking is: how can I force token authentication even when an user signed in **before** with his username/password using the login form that Devise provides?

**Comment by baschtl** [comment]
Could you just log the user out in this case and use the token for the next login?
