### ISSUE TITLE
Expiring auth token.

### ISSUE THREAD

**Issue by 23ranjan** [baschtl/devise-token_authenticatable#37]
Using devise-token_authenticatable with devise 3.2.4. I want to expire auth token on timeout.

Gemfile.
`gem 'devise', '3.2.4'
gem 'devise-token_authenticatable', '~> 0.1'
`
User.rb
`  devise :database_authenticatable, :async , :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :timeoutable, :token_authenticatable`

devise.rb
`  config.timeout_in = 1.minutes
   config.expire_auth_token_on_timeout = true
`

But after timeout , the auth token does not expire.

Any idea what I am missing here ?

**Comment by 23ranjan** [comment]
For ref here is my devise.rb file -
`Devise.setup do |config|
  config.timeout_in = 45.days
  config.expire_auth_token_on_timeout = true
`
Also according to the wiki provided, on changing my devise as mentioned [here](https://github.com/baschtl/devise-token_authenticatable/#configuration

I am getting error :- `undefined method `secret_key=' for Devise::TokenAuthenticatable:Module`

**Comment by baschtl** [comment]
Hi @23ranjan,

if you use version 0.1 of this gem (cf. https://github.com/baschtl/devise-token_authenticatable/tree/v0.1.0) you will not get the functionality that you are looking for. Expiry of a token has been added much later. Read through the release page to find out about the changes for each version: https://github.com/baschtl/devise-token_authenticatable/releases.
