### ISSUE TITLE
Skip trackable from polling requests

### ISSUE THREAD

**Issue by arizz96** [baschtl/devise-token_authenticatable#43]
https://github.com/plataformatec/devise/issues/953

In my Rails app, we've polling requests using token authentication. This cause an update on the user model every request.

Can't we disable tracking on all token requests and keep the tracking methods only on session's controllers?

I'm talking about the `update_tracked_fields` method. If you see the issue, there's a fork that implement a smart method to skip only on token request, keeping on other devise controllers.

**Comment by baschtl** [comment]
@arizz96 Please have a look at https://github.com/baschtl/devise-token_authenticatable/blob/master/lib/devise/token_authenticatable/model.rb#L12. This might allow you to do what you want without changing the gem.

**Comment by baschtl** [comment]
Closing this because of no reaction.
