### ISSUE TITLE
Security issue with devise 4.5.0

### ISSUE THREAD

**Issue by m5rk** [baschtl/devise-token_authenticatable#52]
There is a [security issue with devise 4.5.0](https://github.com/plataformatec/devise/issues/4981). Is this gem compatible with 4.6.0?

**Comment by alexives** [comment]
I'm also curious about this

**Comment by onyxraven** [comment]
fixed by #50

**Comment by baschtl** [comment]
See https://github.com/baschtl/devise-token_authenticatable/releases/tag/v1.1.0.
