### ISSUE TITLE
authentication_token_created_at is null

### ISSUE THREAD

**Issue by NozzyEz** [baschtl/devise-token_authenticatable#56]
hi there.
So I am trying to set his gem up with my rails/graphql project, but it seems it doesn't write to authentication_token_created_at as those fields are all null in the database, I do get tokens just fine however.

**Comment by selcuktoklucu** [comment]
> hi there.
> So I am trying to set his gem up with my rails/graphql project, but it seems it doesn't write to authentication_token_created_at as those fields are all null in the database, I do get tokens just fine however.

Had the same issue here:
`"authentication_token":null,"authentication_token_created_at":null`

I logged out from UI and then signed back in with API, problem solved 👍
